module.exports = {
  "extends": "airbnb",
  "parser": "babel-eslint",
  "plugins": ["emotion"],
  "rules": {
    "no-unused-vars": "warn",
    "implicit-arrow-linebreak": "off",
    "import/prefer-default-export": "off",
    "import/no-extraneous-dependencies": "off",
    "spaced-comment": "off",
    "object-curly-newline": "off",
    "no-multiple-empty-lines": "off",
    "comma-dangle": "off",
    "padded-blocks": "off",
    "object-curly-spacing": "off",
    "key-spacing": "off",
    "arrow-spacing": "off",
    "no-console": "off",
    "no-lone-blocks": "off",
    "no-underscore-dangle": "off",
    "no-spaced-func": "off",
    "operator-linebreak": "off",
    "no-multi-spaces": "off",
    "arrow-parens": "off",
    "no-return-assign": "error",
    "nonblock-statement-body-position": "off",
    "func-call-spacing": "off",
    "array-bracket-spacing": "off",
    "no-nested-ternary": "off",
    "no-use-before-define": "off",
    "curly": "off",
    "function-paren-newline": "off",
    "no-unexpected-multiline": "off",
    "comma-spacing": "off",
    "space-infix-ops": "off",
    "object-property-newline": "off",
    "no-confusing-arrow": "off",
    "dot-notation": "off",
    "quote-props": [ "error", "consistent-as-needed" ],
    "react/jsx-filename-extension": "off",
    "react/destructuring-assignment": ["always", { "ignoreClassFields": true }],
    "jsx-quotes": "off",
    "emotion/syntax-preference": [2, "string"],
  },
  "env": {
    "node": true,
    "browser": true,
    "es6": true
  }
}
